#!/usr/bin/env python
import mmap
import os
import struct

IDX_PSWA = 0
IDX_PSWM = 1
IDX_GPR0 = 2
IDX_GPR15 = 17
IDX_MAX = 18
FLAG_INSN = 1 << 36
NAMES = ['PSWA', 'PSWM'] + ['GPR%d' % i for i in range(16)]


def get_ilen(opc):
    ilc = opc >> 6
    if ilc == 0:
        return 2
    elif ilc == 1 or ilc == 2:
        return 4
    else:
        return 6


insns = {}
fd = os.open('ptracer.out', os.O_RDONLY)
try:
    n = os.fstat(fd).st_size
    m = mmap.mmap(fd, n, access=mmap.ACCESS_READ)
    try:
        i = 0
        values = [0] * IDX_MAX
        while i < n:
            header, = struct.unpack('>Q', m[i:i + 8])
            i += 8
            j = 0
            d = 56
            while j < IDX_MAX:
                if (header & (1 << j)) != 0:
                    values[j], = struct.unpack('>Q', m[i:i + 8])
                    i += 8
                if (header & (1 << (IDX_MAX + j))) != 0:
                    delta = (header >> d) & 0xff
                    if delta >= 128:
                        delta -= 256
                    values[j] += delta
                    values[j] &= 0xffffffffffffffff
                    d -= 8
                print('%-6s %.16X' % (NAMES[j], values[j]))
                j += 1
            pswa = values[IDX_PSWA]
            if (header & FLAG_INSN) == 0:
                insn = insns[pswa]
            else:
                ilen = get_ilen(ord(m[i]))
                insn = m[i:i + ilen]
                i += ilen
                insns[pswa] = insn
            print('INSN   ' + ' '.join(
                    '%.2X' % ord(insn_byte)
                    for insn_byte in insn))
            print('')
    finally:
        m.close()
finally:
    os.close(fd)
